version: '3'

services:
  jenkins:
    image: aapurva/jenkins-build-agent:v1.0
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-sonar-network
    restart: always

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:h2:tcp://sonarqube-db/sonar
    networks:
      - jenkins-sonar-network
    depends_on:
      - sonarqube-db
    restart: always

  sonarqube-db:
    image: postgres:alpine
    container_name: sonarqube-db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - jenkins-sonar-network
    volumes:
      - sonarqube-db:/var/lib/postgresql/data
    restart: always

  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - jenkins-sonar-network
  #   restart: always    

networks:
  jenkins-sonar-network:
    driver: bridge

volumes:
  jenkins_home:
  sonarqube-db:
