name: Build and Push Docker image to the Registry

on:
  workflow_dispatch: 
    inputs: 
      myVersion: 
        description: 'Input Version' 
      myValues: 
        description: 'Input Values'
env:
   TEST_TAG: ${{ secrets.IMAGE_TAGS }}:latest

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push to  the Dockerhub
        env:
         REPO_NAME: "custom-images"
         DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=registry,ref=${{ env.TEST_TAG }}
          cache-to: type=inline


            